name: drones
channels:
  - defaults
dependencies:
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - async-timeout==4.0.3
      - attrs==23.2.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.20.0
      - dill==0.3.8
      - docopt==0.6.2
      - farama-notifications==0.0.4
      - filelock==3.14.0
      - fonttools==4.52.1
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.0.3
      - grpcio==1.64.0
      - gymnasium==0.29.1
      - huggingface-hub==0.23.4
      - huggingface-sb3==3.0
      - idna==3.7
      - imitation==1.0.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpickle==3.0.4
      - kiwisolver==1.4.5
      - mako==1.3.5
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mdurl==0.1.2
      - mpi4py==3.1.6
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - munch==4.0.0
      - networkx==3.3
      - numpy==1.26.4
      - opencv-python==4.9.0.80
      - optuna==3.6.1
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - protobuf==4.25.3
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pybullet==3.2.6
      - pygame==2.5.2
      - pygments==2.18.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - requests==2.32.3
      - rich==13.7.1
      - sacred==0.8.5
      - sb3-contrib==2.3.0
      - scikit-learn==1.5.1
      - scipy==1.13.1
      - seals==0.2.1
      - six==1.16.0
      - smmap==5.0.1
      - sqlalchemy==2.0.31
      - stable-baselines3==2.3.2
      - sympy==1.12
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - torch==2.3.0
      - tqdm==4.66.4
      - transforms3d==0.4.1
      - triton==2.3.0
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - wasabi==1.1.3
      - werkzeug==3.0.3
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4